package gcam.vn.gbot.manager.event

/**
 * Created by thuythu on 12/01/2018.
 */
class EventDefine{
    companion object {
        val NEW_MESSAGE_CHAT = "NEW_MESSAGE_CHAT"
        val NEW_LOGIN_CHAT = "NEW_LOGIN_CHAT"
        val ERROR_CHAT = "ERROR_CHAT"
        val CLICK_FRIEND_ITEM_VIEW = "CLICK_FRIEND_ITEM_VIEW"
        val CLICK_FRIEND_ITEM_BUTTON = "CLICK_FRIEND_ITEM_BUTTON"
        val CLICK_FRIEND_ITEM_DETAILS_RES = "CLICK_FRIEND_ITEM_DETAILS_RES"
        val CLICK_FRIEND_ITEM_MENU_RES = "CLICK_FRIEND_ITEM_MENU_RES"
        val CLICK_FRIEND_ITEM_ONE_VIEW = "CLICK_FRIEND_ITEM_ONE_VIEW"
        val CLICK_FRIEND_ITEM_ONE_ACTION = "CLICK_FRIEND_ITEM_ONE_ACTION"
        val CLICK_SUGGESTION = "CLICK_SUGGESTION"
        val CLICK_FRIEND_TEXT = "CLICK_FRIEND_TEXT"
        val CLICK_FRIEND_ITEM_IMAGE = "CLICK_FRIEND_ITEM_IMAGE"
        val DISSMISS_WEBVIEW = "DISSMISS_WEBVIEW"
        val CLICK_DELETE_TAG_SEARCH = "CLICK_DELETE_TAG_SEARCH"
        val DONE_POST_KNHT = "DONE_POST_KNHT"
    }
}