package gcam.vn.gbot.manager.event

/**
 * Created by thuythu on 12/01/2018.
 */
class EventDefine{
    companion object {
        val NEW_MESSAGE_CHAT = "NEW_MESSAGE_CHAT"
        val NEW_LOGIN_CHAT = "NEW_LOGIN_CHAT"
        val ERROR_CHAT = "ERROR_CHAT"
        val CLICK_FRIEND_ITEM_VIEW = "CLICK_FRIEND_ITEM_VIEW"
        val CLICK_FRIEND_ITEM_BUTTON = "CLICK_FRIEND_ITEM_BUTTON"
        val CLICK_FRIEND_ITEM_ONE_VIEW = "CLICK_FRIEND_ITEM_ONE_VIEW"
        val CLICK_FRIEND_ITEM_ONE_BUTTON = "CLICK_FRIEND_ITEM_ONE_BUTTON"
        val CLICK_SUGGESTION = "CLICK_SUGGESTION"
        val CLICK_FRIEND_TEXT = "CLICK_FRIEND_TEXT"
        val CLICK_FRIEND_ITEM_IMAGE = "CLICK_FRIEND_ITEM_IMAGE"
    }
}